function[DM,AL,R1,R2,TH,P1,P2]=NEDATA(NE,TT,EYOUNG,PO,RR,PRESS,IPLANE)
R1=RR(NE);R2=RR(NE+1);TH=TT(NE);P1=PRESS(NE);P2=PRESS(NE+1);
AL=(R2-R1);
DM=zeros(3,3);%２次元の[D]行列
POE=PO;
EYOUNGE=EYOUNG;
if ((IPLANE == 1) | (IPLANE == 3))%平面ひずみの場合
 POE=PO/(1-PO);
 EYOUNGE=EYOUNG/(1-PO^2);
end
C=EYOUNGE/(1-POE*POE);
DM(1,1)=C;DM(2,2)=C;DM(1,2)=C*POE;DM(2,1)=C*POE;
DM(3,3)=C*0.5*(1-POE);
